### ISSUE TITLE
_getScrollContainer()

### ISSUE THREAD

**Issue by Mephiztopheles** [expandtheroom/jquery-infinite-scroll-helper#11]
please make an option to decide if the container uses a styled scrollbar like niceScroll or fancyScroll

**Comment by garygreen** [comment]
Massive +1. I'm struggling with this plugin because you currently have to specifically define `overflow-y: scroll` on the element you want it to trigger scrolling for - this isn't ideal because it means there is always a scrollbar visible, even when it's not needed. An option to force it to use the actual container element would be much welcome.

**Comment by garygreen** [comment]
@rogden how do you feel about changing the way `_getScrollContainer()` works to instead find the closest element that actually has a scrollbar? There is a pretty neat bit of js to detect when elements have an actual scrollbar - http://stackoverflow.com/questions/4814398/how-can-i-check-if-a-scrollbar-is-visible

Also an option to force it use a particular scroll container would be good, at least as a start ! 😄

**Comment by Mephiztopheles** [comment]
https://github.com/Mephiztopheles/Fancy/blob/master/fancy.js#L510
i am using this to get the closest native-scroll-enabled element

**Comment by rogden** [comment]
@garygreen I think it can be achieved by changing the implementation of _getScrollContainer() so that it checks if the target element is set to overflow/overflow-y scroll **or** auto. This should work because if you don't explicitly set the overflow/y property to auto or scroll, the container will always grow in height to fit its content. So it is safe to assume it will have one of those two values it needs to be scrollable. It would perform the same check up the parent tree to find the first element that meets this requirement if the target element did not.

What do you think?

**Comment by rogden** [comment]
@Mephiztopheles Thanks for pointing me to your implementation..Thats essentially what I would change it to.

**Comment by garygreen** [comment]
@rogden sounds good. When will you release new version? 😜

**Comment by rogden** [comment]
Version 1.2.2 is released and should now find the correct scroll container (checks for overflow/y scroll/auto).
